export const state = {
    currentUser: null,
    titleClickCount: 0,
    spotifyToken: null,
    isRainbowMode: false,
    sortAsc: false,
    albums: [],
    todos: [],
    todoEditIdx: -1,
    slopG: [],
    rareLimit: 3,
    charts: {},
    editIdx: -1,
    currentPage: 1,
    itemsPerPage: 25,
    topSortAsc: false,
    catDeath: [],
    catBlack: [],
    catCore: [],
    catHeavy: [],
    catEtc: [],
    catNonMetal: [],
    currentGenreLevel: "main",
    currentSortField: "",
    currentSortAsc: true
};
