export const COUNTRY_ALPHA3_TO_ALPHA2 = {
    HUN: "hu",
    USA: "us",
    SWE: "se",
    FIN: "fi",
    DEU: "de",
    GBR: "gb",
    NOR: "no",
    FRA: "fr",
    ITA: "it",
    CAN: "ca",
    AUS: "au",
    JPN: "jp",
    BRA: "br",
    POL: "pl",
    GRC: "gr",
    UKR: "ua",
    CZE: "cz",
    CHE: "ch",
    AUT: "at",
    BEL: "be",
    NLD: "nl",
    RUS: "ru",
    ESP: "es",
    PRT: "pt",
    DNK: "dk",
    IRL: "ie",
    ARG: "ar",
    MEX: "mx",
    CHL: "cl",
    COL: "co",
    ISR: "il",
    TUR: "tr",
    IRN: "ir",
    IND: "in",
    CHN: "cn",
    KOR: "kr",
    IDN: "id",
    THA: "th",
    PHL: "ph",
    MYS: "my",
    SGP: "sg",
    NZL: "nz",
    ZAF: "za",
    EGY: "eg",
    MAR: "ma",
    DZA: "dz",
    TUN: "tn",
    SRB: "rs",
    HRV: "hr",
    SVN: "si",
    SVK: "sk",
    ROU: "ro",
    BGR: "bg",
    LTU: "lt",
    LVA: "lv",
    EST: "ee",
    ISL: "is",
    LUX: "lu",
    MLT: "mt",
    CYP: "cy",
    GEO: "ge",
    ARM: "am",
    KAZ: "kz",
    UZB: "uz",
    BGD: "bd",
    PAK: "pk",
    VNM: "vn",
    TWN: "tw",
    HKG: "hk",
    MMR: "mm",
    KHM: "kh",
    LAO: "la",
    MNG: "mn",
    NPL: "np",
    LKA: "lk",
    AFG: "af",
    IRQ: "iq",
    SAU: "sa",
    ARE: "ae",
    QAT: "qa",
    KWT: "kw",
    LBN: "lb",
    JOR: "jo",
    SYR: "sy",
    PSE: "ps",
    PER: "pe",
    VEN: "ve",
    ECU: "ec",
    BOL: "bo",
    PRY: "py",
    URY: "uy",
    CUB: "cu",
    PRI: "pr",
    DOM: "do",
    JAM: "jm",
    HTI: "ht",
    TTO: "tt",
    PAN: "pa",
    CRI: "cr",
    GTM: "gt",
    HND: "hn",
    SLV: "sv",
    NIC: "ni",
    NGA: "ng",
    GHA: "gh",
    KEN: "ke",
    ETH: "et",
    SOM: "so",
    UGA: "ug",
    TZA: "tz",
    SEN: "sn",
    CMR: "cm",
    COD: "cd",
    COG: "cg",
    AGO: "ao",
    MOZ: "mz",
    ZWE: "zw",
    ZMB: "zm",
    BWA: "bw",
    NAM: "na",
    MWI: "mw",
    MLI: "ml",
    NER: "ne",
    TCD: "td",
    SDN: "sd",
    SSD: "ss",
    RWA: "rw",
    BDI: "bi",
    CIV: "ci",
    TGO: "tg",
    BEN: "bj",
    BFA: "bf",
    SLE: "sl",
    LBR: "lr",
    GMB: "gm",
    GIN: "gn",
    GNB: "gw",
    MRT: "mr",
    ESH: "eh",
    GAB: "ga",
    GNQ: "gq",
    STP: "st",
    LSO: "ls",
    SWZ: "sz",
    DJI: "dj",
    ERI: "er",
    COM: "km",
    MUS: "mu",
    SYC: "sc",
    MDG: "mg"
};

export const COUNTRY_NAME_TO_CODE = {
    // Europe
    "hungary": "HUN", "hungarian": "HUN", "magyarorszag": "HUN", "magyar": "HUN",
    "usa": "USA", "united states": "USA", "united states of america": "USA", "america": "USA", "american": "USA", "us": "USA",
    "sweden": "SWE", "swedish": "SWE", "sverige": "SWE",
    "finland": "FIN", "finnish": "FIN", "suomi": "FIN",
    "germany": "DEU", "german": "DEU", "deutschland": "DEU",
    "uk": "GBR", "united kingdom": "GBR", "great britain": "GBR", "britain": "GBR", "england": "GBR", "english": "GBR", "scottish": "GBR", "british": "GBR", "wales": "GBR", "welsh": "GBR", "scotland": "GBR",
    "norway": "NOR", "norwegian": "NOR", "norge": "NOR",
    "france": "FRA", "french": "FRA",
    "italy": "ITA", "italian": "ITA", "italia": "ITA",
    "canada": "CAN", "canadian": "CAN",
    "australia": "AUS", "australian": "AUS",
    "japan": "JPN", "japanese": "JPN", "nippon": "JPN",
    "brazil": "BRA", "brazilian": "BRA", "brasil": "BRA",
    "poland": "POL", "polish": "POL", "polska": "POL",
    "greece": "GRC", "greek": "GRC", "hellas": "GRC",
    "ukraine": "UKR", "ukrainian": "UKR",
    "czechia": "CZE", "czech republic": "CZE", "czech": "CZE", "cesko": "CZE",
    "switzerland": "CHE", "swiss": "CHE",
    "austria": "AUT", "austrian": "AUT",
    "belgium": "BEL", "belgian": "BEL",
    "netherlands": "NLD", "dutch": "NLD", "holland": "NLD", "nederland": "NLD",
    "russia": "RUS", "russian": "RUS",
    "spain": "ESP", "spanish": "ESP", "espana": "ESP",
    "portugal": "PRT", "portuguese": "PRT",
    "denmark": "DNK", "danish": "DNK", "danmark": "DNK",
    "ireland": "IRL", "irish": "IRL",
    "serbia": "SRB", "serbian": "SRB", "srbija": "SRB",
    "croatia": "HRV", "croatian": "HRV", "hrvatska": "HRV",
    "slovenia": "SVN", "slovenian": "SVN",
    "slovakia": "SVK", "slovak": "SVK", "slovakian": "SVK",
    "romania": "ROU", "romanian": "ROU", "romania": "ROU",
    "bulgaria": "BGR", "bulgarian": "BGR",
    "lithuania": "LTU", "lithuanian": "LTU",
    "latvia": "LVA", "latvian": "LVA",
    "estonia": "EST", "estonian": "EST",
    "iceland": "ISL", "icelandic": "ISL",
    "luxembourg": "LUX",
    "malta": "MLT", "maltese": "MLT",
    "cyprus": "CYP",
    "georgia": "GEO", "georgian": "GEO",
    "armenia": "ARM", "armenian": "ARM",
    // Americas
    "argentina": "ARG", "argentine": "ARG",
    "mexico": "MEX", "mexican": "MEX",
    "chile": "CHL", "chilean": "CHL",
    "colombia": "COL", "colombian": "COL",
    "peru": "PER", "peruvian": "PER",
    "venezuela": "VEN", "venezuelan": "VEN",
    "ecuador": "ECU", "ecuadorian": "ECU",
    "bolivia": "BOL", "bolivian": "BOL",
    "paraguay": "PRY", "paraguayan": "PRY",
    "uruguay": "URY", "uruguayan": "URY",
    "cuba": "CUB", "cuban": "CUB",
    "puerto rico": "PRI",
    "dominican republic": "DOM", "dominican": "DOM",
    "jamaica": "JAM", "jamaican": "JAM",
    "haiti": "HTI", "haitian": "HTI",
    "panama": "PAN", "panamanian": "PAN",
    "costa rica": "CRI", "costa rican": "CRI",
    "guatemala": "GTM", "guatemalan": "GTM",
    "honduras": "HND", "honduran": "HND",
    "el salvador": "SLV", "salvadoran": "SLV",
    "nicaragua": "NIC", "nicaraguan": "NIC",
    // Asia
    "israel": "ISR", "israeli": "ISR",
    "turkey": "TUR", "turkish": "TUR", "turkiye": "TUR",
    "iran": "IRN", "iranian": "IRN",
    "india": "IND", "indian": "IND",
    "china": "CHN", "chinese": "CHN",
    "south korea": "KOR", "korea": "KOR", "korean": "KOR",
    "indonesia": "IDN", "indonesian": "IDN",
    "thailand": "THA", "thai": "THA",
    "philippines": "PHL", "filipino": "PHL",
    "malaysia": "MYS", "malaysian": "MYS",
    "singapore": "SGP",
    "vietnam": "VNM", "vietnamese": "VNM",
    "taiwan": "TWN", "taiwanese": "TWN",
    "hong kong": "HKG",
    "myanmar": "MMR", "burma": "MMR",
    "cambodia": "KHM", "cambodian": "KHM",
    "laos": "LAO",
    "mongolia": "MNG", "mongolian": "MNG",
    "nepal": "NPL", "nepali": "NPL",
    "sri lanka": "LKA",
    "afghanistan": "AFG", "afghan": "AFG",
    "iraq": "IRQ", "iraqi": "IRQ",
    "saudi arabia": "SAU", "saudi": "SAU",
    "uae": "ARE", "united arab emirates": "ARE", "dubai": "ARE",
    "qatar": "QAT",
    "kuwait": "KWT",
    "lebanon": "LBN", "lebanese": "LBN",
    "jordan": "JOR",
    "syria": "SYR", "syrian": "SYR",
    "palestine": "PSE", "palestinian": "PSE",
    "kazakhstan": "KAZ", "kazakh": "KAZ",
    "uzbekistan": "UZB", "uzbek": "UZB",
    "bangladesh": "BGD",
    "pakistan": "PAK", "pakistani": "PAK",
    // Africa
    "nigeria": "NGA", "nigerian": "NGA",
    "ghana": "GHA",
    "kenya": "KEN", "kenyan": "KEN",
    "ethiopia": "ETH", "ethiopian": "ETH",
    "somalia": "SOM", "somali": "SOM",
    "uganda": "UGA", "ugandan": "UGA",
    "tanzania": "TZA", "tanzanian": "TZA",
    "senegal": "SEN", "senegalese": "SEN",
    "cameroon": "CMR", "cameroonian": "CMR",
    "congo": "COD", "congolese": "COD", "drc": "COD", "dr congo": "COD",
    "congo brazzaville": "COG",
    "angola": "AGO", "angolan": "AGO",
    "mozambique": "MOZ", "mozambican": "MOZ",
    "zimbabwe": "ZWE", "zimbabwean": "ZWE",
    "zambia": "ZMB", "zambian": "ZMB",
    "botswana": "BWA",
    "namibia": "NAM", "namibian": "NAM",
    "malawi": "MWI", "malawian": "MWI",
    "mali": "MLI",
    "niger": "NER",
    "chad": "TCD",
    "sudan": "SDN", "sudanese": "SDN",
    "south sudan": "SSD",
    "rwanda": "RWA", "rwandan": "RWA",
    "burundi": "BDI",
    "ivory coast": "CIV", "cote d'ivoire": "CIV",
    "togo": "TGO",
    "benin": "BEN",
    "burkina faso": "BFA",
    "sierra leone": "SLE",
    "liberia": "LBR", "liberian": "LBR",
    "gambia": "GMB",
    "guinea": "GIN",
    "guinea-bissau": "GNB",
    "mauritania": "MRT",
    "western sahara": "ESH",
    "gabon": "GAB",
    "equatorial guinea": "GNQ",
    "sao tome": "STP",
    "lesotho": "LSO", "basotho": "LSO",
    "swaziland": "SWZ", "eswatini": "SWZ",
    "djibouti": "DJI",
    "eritrea": "ERI",
    "comoros": "COM",
    "mauritius": "MUS",
    "seychelles": "SYC",
    "madagascar": "MDG", "malagasy": "MDG",
    "egypt": "EGY", "egyptian": "EGY",
    "morocco": "MAR", "moroccan": "MAR",
    "algeria": "DZA", "algerian": "DZA",
    "tunisia": "TUN", "tunisian": "TUN",
    "libya": "LBY", "libyan": "LBY",
    "south africa": "ZAF", "south african": "ZAF",
    // Oceania
    "new zealand": "NZL", "kiwi": "NZL",
    "fiji": "FJI",
    "papua new guinea": "PNG"
};

export function normalizeCountryCode(input) {
    if (!input) return "";
    const trimmed = input.trim();
    if (trimmed.length === 0) return "";

    // If already 3-letter code, return uppercase
    if (/^[A-Za-z]{3}$/.test(trimmed)) {
        const upper = trimmed.toUpperCase();
        if (COUNTRY_ALPHA3_TO_ALPHA2[upper]) {
            return upper;
        }
        return upper;
    }

    // Try to match country name
    const lower = trimmed.toLowerCase();
    if (COUNTRY_NAME_TO_CODE[lower]) {
        return COUNTRY_NAME_TO_CODE[lower];
    }

    // Try partial match for longer inputs
    if (trimmed.length >= 3) {
        for (const [name, code] of Object.entries(COUNTRY_NAME_TO_CODE)) {
            if (name.startsWith(lower)) {
                return code;
            }
        }
    }

    return "";
}

export function getCountryFlag(countryCode) {
    if (!countryCode) return "";
    const code = countryCode.toUpperCase();
    const alpha2 = COUNTRY_ALPHA3_TO_ALPHA2[code];
    if (!alpha2) return "";
    return `<img src="https://flagcdn.com/16x12/${alpha2}.png" width="16" height="12" alt="${code}" style="vertical-align: middle; margin-left: 8px; border-radius: 2px;">`;
}
